//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VAICOM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VAICOM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3_Way_Small_Down {
            get {
                object obj = ResourceManager.GetObject("_3_Way_Small_Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3_Way_Small_Mid {
            get {
                object obj = ResourceManager.GetObject("_3_Way_Small_Mid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3_Way_Small_Up {
            get {
                object obj = ResourceManager.GetObject("_3_Way_Small_Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- VAICOM PRO server-side script
        ///-- common.lua (append)
        ///-- www.vaicompro.com
        ///
        ///function make(self, message)
        ///	
        ///	local role = self:findRole(message.event)
        ///	base.assert(role ~= nil)
        ///	local roleData = role
        ///	local country = getCountry(message)
        ///	local messageModuleName = nil
        ///	local messageLanguage = nil
        ///	local module = getModuleName(message)
        ///	local desiredLanguage = languageByCountry[country]
        ///	if 	module ~= nil and
        ///		roleData.modules ~= nil then
        ///		local messageModuleAndLanguage = 	getMessageModuleA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Append_Core_common {
            get {
                return ResourceManager.GetString("Append_Core_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local vaicomlfs = require(&apos;lfs&apos;); dofile(vaicomlfs.writedir()..[[Scripts\VAICOMPRO\VAICOMPRO.export.lua]]).
        /// </summary>
        public static string Append_Core_Export {
            get {
                return ResourceManager.GetString("Append_Core_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- VAICOM PRO server-side script
        ///-- gameMessages.lua (append)
        ///-- www.vaicompro.com
        ///
        ///function show()
        ///    makeExist()
        ///    
        ///    selectHmdSkin()
        ///
        ///    window:setVisible(false)
        ///end.
        /// </summary>
        public static string Append_Core_gameMessages {
            get {
                return ResourceManager.GetString("Append_Core_gameMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- VAICOM PRO server-side script
        ///-- RadioCommandDialogsPanel.lua (append)
        ///-- www.vaicompro.com
        ///
        ///base.package.path  = base.package.path..&quot;;.\\LuaSocket\\?.lua;&quot;
        ///base.package.cpath = base.package.cpath..&quot;;.\\LuaSocket\\?.dll;&quot;
        ///
        ///local	socket 		= base.require(&apos;socket&apos;)
        ///local 	JSON    	= base.require(&apos;JSON&apos;)
        ///local 	dcsoptions 	= base.require(&apos;optionsEditor&apos;)
        ///local   Gui         = base.require(&apos;dxgui&apos;)
        ///
        ///local colorByRecepientState = {
        ///		[RecepientState.VOID] 				= utils.COLOR.LIGHT_GRAY,	 
        ///		[Recepi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Append_Core_RadioCommandDialogsPanel {
            get {
                return ResourceManager.GetString("Append_Core_RadioCommandDialogsPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- VAICOM PRO server-side script
        ///-- speech.lua (append)
        ///-- www.vaicompro.com
        ///
        ///function make(message)
        ///	if message.type == base.Message.type.TYPE_MORZE then
        ///		return p.morze(message.string, message.parameters.type)
        ///	else
        ///		base.assert(message.sender ~= nil)
        ///		local country = getCountry(message)
        ///		local stateProtocol = nil
        ///		if country then
        ///			stateProtocol = protocolByCountry[country] or defaultProtocol
        ///		else
        ///			stateProtocol = &apos;common&apos;
        ///		end	
        ///		local protocol = protocols[stateProtocol]
        ///		ba [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Append_Core_speech {
            get {
                return ResourceManager.GetString("Append_Core_speech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- VAICOM PRO server-side script
        ///-- TabSheetBar.lua (append)
        ///-- www.vaicompro.com
        ///
        ///function construct(self)
        ///	self.skin = {
        ///		container = {},
        ///		item = Skin.staticSkin(),
        ///		selectedItem = Skin.staticSkin(),
        ///		arrows = Skin.staticSkin(),
        ///		spacing = 0,        
        ///	}
        ///
        ///    self.window = Window.new(0,0,1280,30)
        ///    self.window:setHasCursor(false)
        ///    self.window:setVisible(false)
        ///    
        ///	self.container = Panel.new()
        ///	self.container:setSkin(self.skin.container)
        ///	local x, y, width, height = self.conta [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Append_Core_TabSheetBar {
            get {
                return ResourceManager.GetString("Append_Core_TabSheetBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- VAICOM PRO server-side script
        ///-- VAICOMPRO.export.lua
        ///-- www.vaicompro.com
        ///
        ///package.path  = package.path..&quot;;.\\LuaSocket\\?.lua;&quot;
        ///package.cpath = package.cpath..&quot;;.\\LuaSocket\\?.dll;&quot;
        ///
        ///local socket = require(&quot;socket&quot;)
        ///
        ///local purge
        ///
        ///vaicom = {}
        ///
        ///vaicom.config = {
        ///
        ///		sendtoradio =		{ -- do not edit
        ///							address	= &quot;127.0.0.1&quot;,
        ///							port	= 33334,
        ///							timeout = 0,
        ///							},
        ///							
        ///		receivefromclient =	{ -- do not edit
        ///							address	= &quot;*&quot;,
        ///							port	= 33491,
        ///							timeout  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Append_Core_VAICOMPRO_export {
            get {
                return ResourceManager.GetString("Append_Core_VAICOMPRO_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- VAICOM PRO server-side script
        ///-- JesterAI_Page.lua
        ///-- www.vaicompro.com
        ///
        ///dofile(LockOn_Options.common_script_path..&quot;devices_defs.lua&quot;)
        ///dofile(LockOn_Options.common_script_path..&quot;ViewportHandling.lua&quot;)
        ///
        ///scale = 1.0 
        ///local cx = 0 
        ///local cy = 0 
        ///local aspect = 1
        ///local alpha = 0 
        ///
        ///if GetSelf():is_VR() == false then 
        ///	local viewJester = find_viewport(&quot;F14_JESTER_MENU&quot;) or find_viewport(&quot;GU_MAIN_VIEWPORT&quot;)
        ///	if viewJester == nil then
        ///		viewJester = {
        ///		x = 0;
        ///		y = 0;
        ///		width = LockOn_Options [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Append_F14_JesterAI_Page {
            get {
                return ResourceManager.GetString("Append_F14_JesterAI_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dofile(LockOn_Options.common_script_path..&quot;devices_defs.lua&quot;)
        ///dofile(LockOn_Options.script_path..&quot;materials.lua&quot;)
        ///
        ///indicator_type  = indicator_types.COMMON --0
        ///purposes = {render_purpose.SCREENSPACE_INSIDE_COCKPIT,render_purpose.HUD_ONLY_VIEW} --{}
        ///screenspace_scale = 4;
        ///
        ///-------PAGE IDs-------
        ///id_Page =
        ///{
        ///	MAIN = 0,
        ///}
        ///
        ///id_pagesubset =
        ///{
        ///	COMMON   = 0,
        ///}
        ///
        ///page_subsets = {}
        ///page_subsets[id_pagesubset.COMMON] = LockOn_Options.script_path..&quot;Scripts/JesterAI/JesterAI_Page.lua&quot;
        ///  	
        ///--------- [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Append_F14_JesterInit {
            get {
                return ResourceManager.GetString("Append_F14_JesterInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- VAICOM PRO server-side script
        ///-- 1.lua
        ///-- www.vaicompro.com
        ///
        ///dofile(LockOn_Options.common_script_path..&quot;KNEEBOARD/indicator/definitions.lua&quot;)
        ///dofile(LockOn_Options.common_script_path..&quot;VAICOMPRO/device/VAICOMPRO_Common.lua&quot;)
        ///
        ///add_text     = function(text,UL_X,UL_Y,A,S)
        ///
        ///local UL_X = UL_X or 0
        ///local UL_Y = UL_Y or 0
        ///
        ///local default_char_height  = 0.008
        ///local default_char_width   = 0.3 * default_char_height
        ///local txt 	    					= CreateElement &quot;ceStringPoly&quot;
        ///	  txt.value 					= text
        ///	  txt.ma [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Append_Kneeboard_1 {
            get {
                return ResourceManager.GetString("Append_Kneeboard_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local count = 2999
        ///local function counter()
        ///	count = count + 1
        ///	return count
        ///end
        ///
        ///device_commands =
        ///{
        ///	Master_Reset					= counter(),
        ///
        ///    Select_Page_01                  = counter(),
        ///    Select_Page_02                  = counter(),
        ///    Select_Page_03                  = counter(),
        ///    Select_Page_04                  = counter(),
        ///    Select_Page_05                  = counter(),
        ///    Select_Page_06                  = counter(),
        ///    Select_Page_07                  = counter(),
        ///    Select_Page_08 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Append_Kneeboard_command_defs {
            get {
                return ResourceManager.GetString("Append_Kneeboard_command_defs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local VAICOM_id = 255
        ///
        ///if not creators then 
        ///	creators = {}
        ///end
        ///
        ///creators[VAICOM_id] = {&quot;avLuaDevice&quot;,LockOn_Options.common_script_path..&quot;VAICOMPRO/device/VAICOMPRO_Device.lua&quot;}
        ///
        ///if not devices then
        ///	devices = {}
        ///end
        ///
        ///devices[&quot;VAICOMPRO&quot;] = VAICOM_id
        ///
        ///
        ///
        ///
        ///
        ///
        ///.
        /// </summary>
        public static string Append_Kneeboard_declare_VAICOMPRO_device {
            get {
                return ResourceManager.GetString("Append_Kneeboard_declare_VAICOMPRO_device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --------------------------------------
        ///
        ///local file_exists = function(filename)
        ///   local f=io.open(filename,&quot;r&quot;)
        ///   if f~=nil then 
        ///	io.close(f) 
        ///	return true 
        ///   else 
        ///	return false 
        ///   end
        ///end
        ///
        ///local file = LockOn_Options.common_script_path..&quot;VAICOMPRO/declare_VAICOMPRO_device.lua&quot;
        ///
        ///if file_exists(file) then
        ///	dofile(file)
        ///end.
        /// </summary>
        public static string Append_Kneeboard_device_init {
            get {
                return ResourceManager.GetString("Append_Kneeboard_device_init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- VAICOM PRO server-side script
        ///-- VAICOMPRO_Common.lua
        ///-- www.vaicompro.com
        ///
        ///logcats = {}
        ///init_logcats = function()
        ///	logcats[&quot;ALL&quot;]   	= &quot;ALL&quot;
        ///	logcats[&quot;LOG&quot;]   	= &quot;LOG&quot;
        ///	logcats[&quot;AOCS&quot;]   	= &quot;AOCS&quot;
        ///	logcats[&quot;JTAC&quot;]   	= &quot;JTAC&quot;
        ///	logcats[&quot;TANKER&quot;]   = &quot;TANKER&quot;
        ///	logcats[&quot;AWACS&quot;]   	= &quot;AWACS&quot;
        ///	logcats[&quot;ATC&quot;]   	= &quot;ATC&quot;
        ///	logcats[&quot;FLIGHT&quot;]   = &quot;FLIGHT&quot;
        ///	logcats[&quot;REF&quot;]	 	= &quot;REF&quot;
        ///	logcats[&quot;NOTES&quot;]   	= &quot;NOTES&quot;
        ///end
        ///
        ///headers = {}
        ///init_headers = function()
        ///	headers[1] = { &quot;TopLeft&quot;, &quot;L&quot;, 0, &quot;T&quot;, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Append_Kneeboard_VAICOMPRO_Common {
            get {
                return ResourceManager.GetString("Append_Kneeboard_VAICOMPRO_Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- VAICOM PRO server-side script
        ///-- VAICOM_Device.lua
        ///-- www.vaicompro.com
        ///
        ///package.path  = package.path..&quot;;.\\Scripts\\?.lua;&quot;
        ///package.path  = package.path..&quot;;.\\LuaSocket\\?.lua;&quot;
        ///package.cpath = package.cpath..&quot;;.\\LuaSocket\\?.dll;&quot;
        ///
        ///local	socket 		= require(&apos;socket&apos;)
        ///local 	JSON    	= require(&apos;JSON&apos;)
        ///
        ///local 	dev = GetSelf()
        ///local 	dev_timer
        ///local 	update_time_step = 0.02
        ///local 	master_opacity = 0.5
        ///
        ///make_default_activity(update_time_step)
        ///need_to_be_closed = false
        ///
        ///local sender
        ///loca [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Append_Kneeboard_VAICOMPRO_Device {
            get {
                return ResourceManager.GetString("Append_Kneeboard_VAICOMPRO_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------ DISABLED ------.
        /// </summary>
        public static string Append_ReplaceString_F14_JesterAI_Page {
            get {
                return ResourceManager.GetString("Append_ReplaceString_F14_JesterAI_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dofile(&apos;Scripts/World/Radio/ModulationTypes.lua&apos;)
        ///dofile(&apos;Scripts/World/Radio/FrequencyBands.lua&apos;)
        ///
        ///local gettext = require(&quot;i_18n&quot;)
        ///local       _ = gettext.translate
        ///
        ///--WORLD RADIO -- Appended by VaicomPro
        ///
        ///radioTableFormat = 3
        ///radio = {
        ///	{
        ///		radioId = &apos;airfield4_0&apos;;
        ///		role = {&quot;ground&quot;, &quot;tower&quot;, &quot;approach&quot;};
        ///		callsign = {{[&quot;common&quot;] = {_(&quot;BAS100&quot;), &quot;BAS100&quot;}}};
        ///		frequency = {[UHF] = {MODULATIONTYPE_AM, 257100000.000000}};
        ///		sceneObjects = {&apos;t:6021123&apos;};
        ///	};
        ///	{
        ///		radioId = &apos;EFIV_Ivalo1&apos;;
        ///		role = {&quot;ground [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Append_Terrain_Kola_radio {
            get {
                return ResourceManager.GetString("Append_Terrain_Kola_radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dofile(&apos;Scripts/World/Radio/ModulationTypes.lua&apos;)
        ///dofile(&apos;Scripts/World/Radio/FrequencyBands.lua&apos;)
        ///
        ///local gettext = require(&quot;i_18n&quot;)
        ///local       _ = gettext.translate
        ///
        ///--WORLD RADIO -- Appended by VaicomPro
        ///
        ///radioTableFormat = 3
        ///radio = {
        ///	{
        ///		radioId = &apos;airfield6_0&apos;;
        ///		role = {&quot;ground&quot;, &quot;tower&quot;, &quot;approach&quot;};
        ///		callsign = {{[&quot;common&quot;] = {_(&quot;Boulderñity&quot;), &quot;Boulderñity&quot;}}};
        ///		frequency = {[UHF] = {MODULATIONTYPE_AM, 250100000.000000}, [VHF_HI] = {MODULATIONTYPE_AM, 118050000.000000}};
        ///		sceneObjects = {&apos;t:48 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Append_Terrain_Nevada_Radio {
            get {
                return ResourceManager.GetString("Append_Terrain_Nevada_Radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dofile(&apos;Scripts/World/Radio/ModulationTypes.lua&apos;)
        ///dofile(&apos;Scripts/World/Radio/FrequencyBands.lua&apos;)
        ///
        ///local gettext = require(&quot;i_18n&quot;)
        ///local       _ = gettext.translate
        ///
        ///--WORLD RADIO -- Appended by VaicomPro
        ///
        ///radioTableFormat = 3
        ///radio = {
        ///	{
        ///		radioId = &apos;0&apos;;
        ///		role = {&quot;ground&quot;, &quot;tower&quot;, &quot;approach&quot;};
        ///		callsign = {{[&quot;common&quot;] = {_(&quot;Sharqiyah&quot;), &quot;Sharqiyah&quot;}}}; -- Where is this?
        ///		frequency = {};
        ///		sceneObjects = {&apos;t:10379342&apos;};
        ///	};
        ///	{
        ///		radioId = &apos;airfield1_0&apos;;
        ///		role = {&quot;ground&quot;, &quot;tower&quot;, &quot;approach&quot;};
        ///		cal [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Append_Terrain_Siani_radio {
            get {
                return ResourceManager.GetString("Append_Terrain_Siani_radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] base_menu_window {
            get {
                object obj = ResourceManager.GetObject("base_menu_window", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream Blip_A {
            get {
                return ResourceManager.GetStream("Blip_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream Blip_B {
            get {
                return ResourceManager.GetStream("Blip_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream Blip_Error {
            get {
                return ResourceManager.GetStream("Blip_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream Blip_OFF {
            get {
                return ResourceManager.GetStream("Blip_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream Blip_ON {
            get {
                return ResourceManager.GetStream("Blip_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream Blip_Recipient_NA {
            get {
                return ResourceManager.GetStream("Blip_Recipient_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream Blip_Reply {
            get {
                return ResourceManager.GetStream("Blip_Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Button_TX1_IN {
            get {
                object obj = ResourceManager.GetObject("Button_TX1_IN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Button_TX1_OUT {
            get {
                object obj = ResourceManager.GetObject("Button_TX1_OUT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Button_TX2_IN {
            get {
                object obj = ResourceManager.GetObject("Button_TX2_IN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Button_TX2_OUT {
            get {
                object obj = ResourceManager.GetObject("Button_TX2_OUT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Button_TX3_IN {
            get {
                object obj = ResourceManager.GetObject("Button_TX3_IN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Button_TX3_OUT {
            get {
                object obj = ResourceManager.GetObject("Button_TX3_OUT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Button_TX4_IN {
            get {
                object obj = ResourceManager.GetObject("Button_TX4_IN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Button_TX4_OUT {
            get {
                object obj = ResourceManager.GetObject("Button_TX4_OUT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Button_TX5_IN {
            get {
                object obj = ResourceManager.GetObject("Button_TX5_IN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Button_TX5_OUT {
            get {
                object obj = ResourceManager.GetObject("Button_TX5_OUT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Button_TX6_IN {
            get {
                object obj = ResourceManager.GetObject("Button_TX6_IN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Button_TX6_OUT {
            get {
                object obj = ResourceManager.GetObject("Button_TX6_OUT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap buy_now {
            get {
                object obj = ResourceManager.GetObject("buy_now", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Code_Button_Up {
            get {
                object obj = ResourceManager.GetObject("Code_Button_Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to base = _G
        ///
        ///local dev = 38
        ///local arg = 3676
        ///local val = 1
        ///
        ///--local value = base.GetDevice(dev):get_argument_value(arg)
        ///local value = base.GetDevice(dev):performClickableAction(arg,val)
        ///
        ///base.trigger.action.outText(&quot;arg &quot;..arg..&quot; = &quot;..base.tostring(value),5)
        ///
        ///
        ///
        ///
        ///base = _G
        ///local lfs = require(&quot;lfs&quot;)
        ///local io = require(&quot;io&quot;)
        ///dumpfile = io.open(lfs.writedir()..&quot;crawl-x.csv&quot;, &quot;w&quot;)
        ///
        ///if dumpfile then
        ///listtables = function (offset, maxdepth, tablename, filtertype)
        ///if base.type(tablename) == &quot;tab [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Debug_code {
            get {
                return ResourceManager.GetString("Debug_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream delimeter_22050 {
            get {
                return ResourceManager.GetStream("delimeter_22050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream delimeter_44100 {
            get {
                return ResourceManager.GetStream("delimeter_44100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Dial_Switch_Down {
            get {
                object obj = ResourceManager.GetObject("Dial_Switch_Down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Dial_Switch_Up {
            get {
                object obj = ResourceManager.GetObject("Dial_Switch_Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap elbow {
            get {
                object obj = ResourceManager.GetObject("elbow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local self_ID = &quot;VAICOM PRO&quot;
        ///
        ///declare_plugin(self_ID,
        ///{
        ///	installed	 = true,
        ///	dirName		 = current_mod_path,
        ///	binaries	 = {&apos;VAICOMPRO.dll&apos;},
        ///
        ///	displayName	 = &quot;VAICOM PRO&quot;,
        ///	shortName	 = &quot;VAICOM PRO&quot;,
        ///	fileMenuName = &quot;VAICOM PRO&quot;,
        ///
        ///	version		 = &quot;2.9.4&quot;,
        ///	state		 = &quot;installed&quot;, 	
        ///	developerName= &quot;VAICOM Community&quot;,
        ///	info		 = _(&quot;VAICOM PRO Community Edition is a voice communications interface plugin for VoiceAttack, enabling true-to-life radio communications with all AI units in the mission.&quot;),
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string entry {
            get {
                return ResourceManager.GetString("entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---------------------------
        ///MIT License
        ///
        ///Copyright (c) 2022 VAICOM PRO Community Edition
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the f [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EULA {
            get {
                return ResourceManager.GetString("EULA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local vaicomlfs = require(&apos;lfs&apos;); dofile(vaicomlfs.writedir()..[[Scripts\VAICOMPRO\VAICOMPRO.export.lua]]).
        /// </summary>
        public static string Exportmatch {
            get {
                return ResourceManager.GetString("Exportmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap FREE_000_1024x485 {
            get {
                object obj = ResourceManager.GetObject("FREE_000_1024x485", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hazard_sign_images_general_warning {
            get {
                object obj = ResourceManager.GetObject("hazard_sign_images_general_warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Hotmic_OFF {
            get {
                object obj = ResourceManager.GetObject("Hotmic_OFF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Hotmic_ON {
            get {
                object obj = ResourceManager.GetObject("Hotmic_ON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon_38x38 {
            get {
                object obj = ResourceManager.GetObject("icon_38x38", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon_76x76 {
            get {
                object obj = ResourceManager.GetObject("icon_76x76", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon_active {
            get {
                object obj = ResourceManager.GetObject("icon_active", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon_buy {
            get {
                object obj = ResourceManager.GetObject("icon_buy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon_select {
            get {
                object obj = ResourceManager.GetObject("icon_select", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream Low_Blip_Recipient_NA {
            get {
                return ResourceManager.GetStream("Low_Blip_Recipient_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] MainMenulogo {
            get {
                object obj = ResourceManager.GetObject("MainMenulogo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MainMenulogo1 {
            get {
                object obj = ResourceManager.GetObject("MainMenulogo1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap microphone {
            get {
                object obj = ResourceManager.GetObject("microphone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] MS33558 {
            get {
                object obj = ResourceManager.GetObject("MS33558", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] NoLoadContext {
            get {
                object obj = ResourceManager.GetObject("NoLoadContext", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Notepad_png {
            get {
                object obj = ResourceManager.GetObject("Notepad_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Notepad_smudge_png {
            get {
                object obj = ResourceManager.GetObject("Notepad_smudge_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Notepad_watermark_png {
            get {
                object obj = ResourceManager.GetObject("Notepad_watermark_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- VAICOM PRO Theme
        ///
        ///local LeftMargin = 56
        ///
        ///local TitleSkin = {
        ///		[&quot;params&quot;] = {
        ///			[&quot;name&quot;] = &quot;staticOptionsTitleSkin&quot;,
        ///		},
        ///		[&quot;states&quot;] = {
        ///			[&quot;released&quot;] = {
        ///				[1] = {
        ///					[&quot;text&quot;] = {
        ///						[&quot;horzAlign&quot;] = {
        ///							[&quot;type&quot;] = &quot;min&quot;
        ///						}
        ///					}
        ///				}
        ///			}
        ///		}
        ///	}
        ///
        ///
        ///local SubTitleSkin = {
        ///	[&quot;params&quot;] = {
        ///		[&quot;name&quot;] = &quot;staticSkin2&quot;,
        ///	},
        ///	[&quot;states&quot;] = {
        ///		[&quot;released&quot;] = {
        ///			[1] = {
        ///				[&quot;text&quot;] = {
        ///					[&quot;fontSize&quot;] = 10,
        ///					[&quot;horzAlign&quot;] = {
        ///						[&quot;type&quot;] = &quot;min&quot;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string options {
            get {
                return ResourceManager.GetString("options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cdata =
        ///{
        ///	VAICOM_TITLE		= &apos;$HEADER$&apos;,
        ///	VAICOM_VERSION		= &apos;$VERSION$&apos;,
        ///	VAICOM_LICENSE		= &apos;$LICENSE$&apos;,
        ///
        ///	VAICOM_DLLPLUGIN	= &apos;$DLLPLUGIN$&apos;,
        ///	VAICOM_DLLCHATTER	= &apos;$DLLCHATTER$&apos;,
        ///	VAICOM_DLLRIO		= &apos;$DLLRIO$&apos;,
        ///
        ///	VAICOM_IPCONFIG		= &apos;$IPCONFIG$&apos;,
        ///	VAICOM_CLIENTIP_TXT	= &apos;$CLIENTIPTXT$&apos;,
        ///
        ///	VAICOM_FOOTER		= &apos;$FOOTER$&apos;,
        ///}
        ///.
        /// </summary>
        public static string optionsData {
            get {
                return ResourceManager.GetString("optionsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local DbOption = require(&apos;Options.DbOption&apos;)
        ///
        ///return
        ///{
        ///	VAICOMDebugModeEnabled				= DbOption.new():setValue(false):checkbox(),
        ///	VAICOMClientIP						= DbOption.new():setValue(&apos;127.0.0.1&apos;):editbox(),
        ///	AIRIODisableWheel					= DbOption.new():setValue(false):checkbox(),
        ///
        ///}.
        /// </summary>
        public static string optionsDb {
            get {
                return ResourceManager.GetString("optionsDb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Common part of all speech construction protocols
        ///
        ///local base = _G
        ///
        ///module(&apos;common&apos;)
        ///__index = base.getfenv()
        ///
        ///
        ///local p = base.require(&apos;phrase&apos;)
        ///local u = base.require(&apos;utils&apos;)
        ///local math = base.math
        ///--local gettext = base.require(&quot;i_18n&quot;)
        ///--local _ = gettext.translate
        ///local require = base.require
        ///require(&apos;i18n&apos;).setup(_M)
        ///
        ///local print 	= base.print
        ///local tostring 	= base.tostring
        ///local tonumber  = base.tonumber
        ///
        ///local  BIG_CALLSIGN_MIN = 1e9
        ///local  SHT_CALLSIGN_MAX = 1e3
        ///
        ///function c [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Orig_Core_common {
            get {
                return ResourceManager.GetString("Orig_Core_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Orig_Core_Export {
            get {
                return ResourceManager.GetString("Orig_Core_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dofile(&apos;./Scripts/UI/initGUI.lua&apos;)
        ///
        ///local base = _G
        ///
        ///module(&apos;gameMessages&apos;)
        ///
        ///local require = base.require
        ///local pairs = base.pairs
        ///local ipairs = base.ipairs
        ///local print = base.print
        ///local table = base.table
        ///local string = base.string
        ///local tonumber = base.tonumber
        ///local tostring = base.tostring
        ///local assert = base.assert
        ///local type = base.type
        ///local math = base.math
        ///local os = base.os
        ///local HMD = base.HMD
        ///
        ///local Gui               = require(&apos;dxgui&apos;)
        ///local DialogLoader      = require(&apos;Di [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Orig_Core_gameMessages {
            get {
                return ResourceManager.GetString("Orig_Core_gameMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Implementation of Command Dialogs Panel for DCS objects.
        ///--RadioCommandDialogsPanel receives messags (wMessage), world events (world.event), generates internal events and passes them to
        ///--CommandDialogsPanel.onEvent().
        ///--Indicates if at least one of the radios is tuned into the given recepient.
        ///--Selects and tunes radios to the recepient.
        ///
        ///local base = _G
        ///local DCS           = require(&apos;DCS&apos;) 
        ///
        ///local function clean()
        ///	base.RadioCommandDialogsPanel = nil
        ///	base.package.loaded[&apos;RadioCommandDialogsP [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Orig_Core_RadioCommandDialogsPanel {
            get {
                return ResourceManager.GetString("Orig_Core_RadioCommandDialogsPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Speech construction module
        ///
        ///local base = _G
        ///
        ///local function clean()
        ///	base.utils = nil
        ///	base.package.loaded[&apos;utils&apos;] = nil
        ///	base.common = nil
        ///	base.package.loaded[&apos;common&apos;] = nil
        ///	base.NATO = nil
        ///	base.package.loaded[&apos;NATO&apos;] = nil
        ///	base.USSR = nil
        ///	base.package.loaded[&apos;USSR&apos;] = nil
        ///	base.speech = nil
        ///	base.package.loaded[&apos;speech&apos;] = nil
        ///	base.phrase = nil
        ///	base.package.loaded[&apos;phrase&apos;] = nil
        ///end
        ///
        ///clean()
        ///
        ///module(&apos;speech&apos;)
        ///
        ///--Protocol determines how message content (sound files + subt [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Orig_Core_speech {
            get {
                return ResourceManager.GetString("Orig_Core_speech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Upper bar of tab sheet widget
        ///
        ///local base = _G
        ///
        ///module(&apos;TabSheetBar&apos;)
        ///mtab = { __index = _M}
        ///
        ///local Factory = base.require(&apos;Factory&apos;)
        ///local Static = base.require(&quot;Static&quot;)
        ///local Panel = base.require(&quot;Panel&quot;)
        ///local Window = base.require(&quot;Window&quot;)
        ///local Skin = base.require(&quot;Skin&quot;)
        ///
        ///local function getTabWidth(self, index)
        ///	local width, height = self.tabs[index]:calcSize()
        ///	return width
        ///end
        ///
        ///local function getTabAreaWidth(self)
        ///	local x, y, width, height = self.container:getBounds()
        ///	retur [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Orig_Core_TabSheetBar {
            get {
                return ResourceManager.GetString("Orig_Core_TabSheetBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Orig_Core_VAICOMPRO_export {
            get {
                return ResourceManager.GetString("Orig_Core_VAICOMPRO_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dofile(LockOn_Options.common_script_path..&quot;devices_defs.lua&quot;)
        ///dofile(LockOn_Options.common_script_path..&quot;ViewportHandling.lua&quot;)
        ///
        ///local cx = 0
        ///local cy = 0
        ///local aspect = 1
        ///scale = 1
        ///
        ///if GetSelf():is_VR() == false then 
        ///	local viewJester = find_viewport(&quot;F14_JESTER_MENU&quot;) or find_viewport(&quot;GU_MAIN_VIEWPORT&quot;)
        ///	if viewJester == nil then
        ///		viewJester = {
        ///		x = 0;
        ///		y = 0;
        ///		width = LockOn_Options.screen.width;
        ///		height = LockOn_Options.screen.height;
        ///		}
        ///	end
        ///
        ///	cx = ( ( ( viewJester.x + viewJ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Orig_F14_JesterAI_Page {
            get {
                return ResourceManager.GetString("Orig_F14_JesterAI_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dofile(LockOn_Options.common_script_path..&quot;devices_defs.lua&quot;)
        ///dofile(LockOn_Options.script_path..&quot;materials.lua&quot;)
        ///
        ///indicator_type       = indicator_types.COMMON
        ///purposes 	 = {render_purpose.SCREENSPACE_INSIDE_COCKPIT,render_purpose.SCREENSPACE_OUTSIDE_COCKPIT,render_purpose.HUD_ONLY_VIEW}
        ///screenspace_scale    = 4;
        ///
        ///-------PAGE IDs-------
        ///id_Page =
        ///{
        ///	MAIN = 0,
        ///}
        ///
        ///id_pagesubset =
        ///{
        ///	COMMON   = 0,
        ///}
        ///
        ///page_subsets = {}
        ///page_subsets[id_pagesubset.COMMON] = LockOn_Options.script_path..&quot;Scripts [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Orig_F14_JesterInit {
            get {
                return ResourceManager.GetString("Orig_F14_JesterInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dofile(LockOn_Options.common_script_path..&quot;devices_defs.lua&quot;)
        ///dofile(LockOn_Options.common_script_path..&quot;ViewportHandling.lua&quot;)
        ///
        ///local cx = 0
        ///local cy = 0
        ///local aspect = 1
        ///scale = 1
        ///
        ///if GetSelf():is_VR() == false then 
        ///	local viewJester = find_viewport(&quot;F14_JESTER_MENU&quot;) or find_viewport(&quot;GU_MAIN_VIEWPORT&quot;)
        ///	if viewJester == nil then
        ///		viewJester = {
        ///		x = 0;
        ///		y = 0;
        ///		width = LockOn_Options.screen.width;
        ///		height = LockOn_Options.screen.height;
        ///		}
        ///	end
        ///
        ///	cx = ( ( ( viewJester.x + viewJ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Orig_ReplaceString_F14_JesterAI_Page {
            get {
                return ResourceManager.GetString("Orig_ReplaceString_F14_JesterAI_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dofile(&apos;Scripts/World/Radio/ModulationTypes.lua&apos;)
        ///dofile(&apos;Scripts/World/Radio/FrequencyBands.lua&apos;)
        ///
        ///local gettext = require(&quot;i_18n&quot;)
        ///local       _ = gettext.translate
        ///
        ///--WORLD RADIO
        ///
        ///radioTableFormat = 3
        ///radio = {
        ///	{
        ///		radioId = &apos;airfield4_0&apos;;
        ///		role = {&quot;ground&quot;, &quot;tower&quot;, &quot;approach&quot;};
        ///		callsign = {{[&quot;common&quot;] = {_(&quot;BAS100&quot;), &quot;BAS100&quot;}}};
        ///		frequency = {[UHF] = {MODULATIONTYPE_AM, 257100000.000000}};
        ///		sceneObjects = {&apos;t:6021123&apos;};
        ///	};
        ///	{
        ///		radioId = &apos;EFIV_Ivalo1&apos;;
        ///		role = {&quot;ground&quot;, &quot;tower&quot;, &quot;approach&quot;};
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Orig_Terrain_Kola_radio {
            get {
                return ResourceManager.GetString("Orig_Terrain_Kola_radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dofile(&apos;Scripts/World/Radio/ModulationTypes.lua&apos;)
        ///dofile(&apos;Scripts/World/Radio/FrequencyBands.lua&apos;)
        ///
        ///local gettext = require(&quot;i_18n&quot;)
        ///local       _ = gettext.translate
        ///
        ///--WORLD RADIO
        ///
        ///radioTableFormat = 3
        ///radio = {
        ///	{
        ///		radioId = &apos;airfield6_0&apos;;
        ///		role = {&quot;ground&quot;, &quot;tower&quot;, &quot;approach&quot;};
        ///		callsign = {{[&quot;common&quot;] = {_(&quot;Boulderñity&quot;), &quot;Boulderñity&quot;}}};
        ///		frequency = {};
        ///		sceneObjects = {&apos;t:4816956&apos;};
        ///	};
        ///	{
        ///		radioId = &apos;airfield1_0&apos;;
        ///		role = {&quot;ground&quot;, &quot;tower&quot;, &quot;approach&quot;};
        ///		callsign = {{[&quot;common&quot;] = {_(&quot;Ind [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Orig_Terrain_Nevada_Radio {
            get {
                return ResourceManager.GetString("Orig_Terrain_Nevada_Radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dofile(&apos;Scripts/World/Radio/ModulationTypes.lua&apos;)
        ///dofile(&apos;Scripts/World/Radio/FrequencyBands.lua&apos;)
        ///
        ///local gettext = require(&quot;i_18n&quot;)
        ///local       _ = gettext.translate
        ///
        ///--WORLD RADIO
        ///
        ///radioTableFormat = 3
        ///radio = {
        ///	{
        ///		radioId = &apos;0&apos;;
        ///		role = {&quot;ground&quot;, &quot;tower&quot;, &quot;approach&quot;};
        ///		callsign = {{[&quot;common&quot;] = {_(&quot;Sharqiyah&quot;), &quot;Sharqiyah&quot;}}};
        ///		frequency = {};
        ///		sceneObjects = {&apos;t:10379342&apos;};
        ///	};
        ///	{
        ///		radioId = &apos;airfield1_0&apos;;
        ///		role = {&quot;ground&quot;, &quot;tower&quot;, &quot;approach&quot;};
        ///		callsign = {{[&quot;common&quot;] = {_(&quot;AbuSultan&quot;), &quot;Ab [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Orig_Terrain_Siani_radio {
            get {
                return ResourceManager.GetString("Orig_Terrain_Siani_radio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap pdf_page {
            get {
                object obj = ResourceManager.GetObject("pdf_page", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PTT_HOT_Left {
            get {
                object obj = ResourceManager.GetObject("PTT_HOT_Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PTT_HOT_Right {
            get {
                object obj = ResourceManager.GetObject("PTT_HOT_Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream Radio_Noise_Test {
            get {
                return ResourceManager.GetStream("Radio_Noise_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Sidetitle_About {
            get {
                object obj = ResourceManager.GetObject("Sidetitle_About", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Sidetitle_Config {
            get {
                object obj = ResourceManager.GetObject("Sidetitle_Config", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Sidetitle_Edit {
            get {
                object obj = ResourceManager.GetObject("Sidetitle_Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Sidetitle_Help {
            get {
                object obj = ResourceManager.GetObject("Sidetitle_Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Sidetitle_Prefs {
            get {
                object obj = ResourceManager.GetObject("Sidetitle_Prefs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Sidetitle_PTT {
            get {
                object obj = ResourceManager.GetObject("Sidetitle_PTT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Sidetitle_Reset {
            get {
                object obj = ResourceManager.GetObject("Sidetitle_Reset", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream Silence_22kHz_Mono_250ms {
            get {
                return ResourceManager.GetStream("Silence_22kHz_Mono_250ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SRS_Dn {
            get {
                object obj = ResourceManager.GetObject("SRS_Dn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SRS_Up {
            get {
                object obj = ResourceManager.GetObject("SRS_Up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Strip_Help {
            get {
                object obj = ResourceManager.GetObject("Strip_Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Tabs_ALL_png {
            get {
                object obj = ResourceManager.GetObject("Tabs_ALL_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Tabs_AOCS_png {
            get {
                object obj = ResourceManager.GetObject("Tabs_AOCS_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Tabs_ATC_png {
            get {
                object obj = ResourceManager.GetObject("Tabs_ATC_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Tabs_AWACS_png {
            get {
                object obj = ResourceManager.GetObject("Tabs_AWACS_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Tabs_FLIGHT_png {
            get {
                object obj = ResourceManager.GetObject("Tabs_FLIGHT_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Tabs_JTAC_png {
            get {
                object obj = ResourceManager.GetObject("Tabs_JTAC_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Tabs_LOG_png {
            get {
                object obj = ResourceManager.GetObject("Tabs_LOG_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Tabs_NOTES_png {
            get {
                object obj = ResourceManager.GetObject("Tabs_NOTES_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Tabs_REF_png {
            get {
                object obj = ResourceManager.GetObject("Tabs_REF_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Tabs_TANKER_png {
            get {
                object obj = ResourceManager.GetObject("Tabs_TANKER_png", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Tacan_Test_Light_Off {
            get {
                object obj = ResourceManager.GetObject("Tacan_Test_Light_Off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Tacan_Test_Light_On {
            get {
                object obj = ResourceManager.GetObject("Tacan_Test_Light_On", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Tacan_Vol_Knob_1 {
            get {
                object obj = ResourceManager.GetObject("Tacan_Vol_Knob_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TX_button_cover {
            get {
                object obj = ResourceManager.GetObject("TX_button_cover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap UI_2511_BG_About {
            get {
                object obj = ResourceManager.GetObject("UI_2511_BG_About", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap UI_2511_BG_Config {
            get {
                object obj = ResourceManager.GetObject("UI_2511_BG_Config", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap UI_2511_BG_Edit {
            get {
                object obj = ResourceManager.GetObject("UI_2511_BG_Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap UI_2511_BG_Help {
            get {
                object obj = ResourceManager.GetObject("UI_2511_BG_Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap UI_2511_BG_Prefs {
            get {
                object obj = ResourceManager.GetObject("UI_2511_BG_Prefs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap UI_2511_BG_PTT_INV {
            get {
                object obj = ResourceManager.GetObject("UI_2511_BG_PTT_INV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap UI_2511_BG_PTT_MULTI {
            get {
                object obj = ResourceManager.GetObject("UI_2511_BG_PTT_MULTI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap UI_2511_BG_PTT_NORM {
            get {
                object obj = ResourceManager.GetObject("UI_2511_BG_PTT_NORM", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap UI_2511_BG_PTT_SNGL {
            get {
                object obj = ResourceManager.GetObject("UI_2511_BG_PTT_SNGL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap UI_2511_BG_Reset {
            get {
                object obj = ResourceManager.GetObject("UI_2511_BG_Reset", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream UI_Ambiguous {
            get {
                return ResourceManager.GetStream("UI_Ambiguous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream UI_Blocked {
            get {
                return ResourceManager.GetStream("UI_Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream UI_Chime {
            get {
                return ResourceManager.GetStream("UI_Chime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream UI_Click {
            get {
                return ResourceManager.GetStream("UI_Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream UI_Confirmation {
            get {
                return ResourceManager.GetStream("UI_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream UI_Dial_Click {
            get {
                return ResourceManager.GetStream("UI_Dial_Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream UI_Error {
            get {
                return ResourceManager.GetStream("UI_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream UI_Gum_Soft {
            get {
                return ResourceManager.GetStream("UI_Gum_Soft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream UI_Low_Chime {
            get {
                return ResourceManager.GetStream("UI_Low_Chime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream UI_Notify {
            get {
                return ResourceManager.GetStream("UI_Notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream UI_Pushbutton_Soft {
            get {
                return ResourceManager.GetStream("UI_Pushbutton_Soft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream UI_Radio_Noise {
            get {
                return ResourceManager.GetStream("UI_Radio_Noise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream UI_Radio_Noise_ALT {
            get {
                return ResourceManager.GetStream("UI_Radio_Noise_ALT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream UI_RadioClickAfter {
            get {
                return ResourceManager.GetStream("UI_RadioClickAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream UI_RadioClickAfter_Alt {
            get {
                return ResourceManager.GetStream("UI_RadioClickAfter_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream UI_RadioClickBefore {
            get {
                return ResourceManager.GetStream("UI_RadioClickBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream UI_RadioClickBefore_Alt {
            get {
                return ResourceManager.GetStream("UI_RadioClickBefore_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream UI_Recipient_NA {
            get {
                return ResourceManager.GetStream("UI_Recipient_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream UI_Reply {
            get {
                return ResourceManager.GetStream("UI_Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream UI_Squelch_Jet_1 {
            get {
                return ResourceManager.GetStream("UI_Squelch_Jet_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream UI_Squelch_Jet_2 {
            get {
                return ResourceManager.GetStream("UI_Squelch_Jet_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream UI_Squelch_LT {
            get {
                return ResourceManager.GetStream("UI_Squelch_LT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream UI_Switch_Soft {
            get {
                return ResourceManager.GetStream("UI_Switch_Soft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ECHO OFF
        ///ECHO VAICOM PRO Commnity Edition 2.9
        ///ECHO Extension Updater running...
        ///ECHO Closing VoiceAttack...
        ///TASKKILL /F /IM VoiceAttack.exe
        ///TIMEOUT /T 2
        ///ECHO Updating files... 
        ///COPY /Y &quot;Updates\Package\VAICOMPRO\Extensions\Chatter.dll&quot; &quot;Extensions\Chatter.dll&quot; 
        ///RMDIR /S /Q &quot;Updates&quot;
        ///ECHO Restarting VoiceAttack...
        ///START &quot;VoiceAttack&quot; /MIN XXXXXX
        ///ECHO Done!
        ///EXIT
        ///.
        /// </summary>
        public static string Updater_Chatter {
            get {
                return ResourceManager.GetString("Updater_Chatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ECHO OFF
        ///ECHO VAICOM PRO 2.9
        ///ECHO Plugin Updater running...
        ///ECHO Closing VoiceAttack...
        ///TASKKILL /F /IM VoiceAttack.exe
        ///TIMEOUT /T 2
        ///ECHO Updating files...
        ///COPY /Y &quot;Updates\Package\VAICOMPRO\Documentation\VAICOM PRO Community User Manual.pdf&quot; &quot;Documentation\VAICOM PRO Community User Manual.pdf&quot; 
        ///COPY /Y &quot;Updates\Package\VAICOMPRO\EULA.txt&quot; &quot;EULA.txt&quot; 
        ///COPY /Y &quot;Updates\Package\VAICOMPRO\VAICOMPRO.dll&quot; &quot;VAICOMPRO.dll&quot; 
        ///RMDIR /S /Q &quot;Updates&quot;
        ///DEL /Q VAICOMPRO.exe
        ///ECHO Restarting VoiceAttack...
        ///STA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Updater_Plugin {
            get {
                return ResourceManager.GetString("Updater_Plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ECHO OFF
        ///ECHO VAICOM PRO Community Edition 2.9
        ///ECHO Extension Updater running...
        ///ECHO Closing VoiceAttack...
        ///TASKKILL /F /IM VoiceAttack.exe
        ///TIMEOUT /T 2
        ///ECHO Updating files... 
        ///COPY /Y &quot;Updates\Package\VAICOMPRO\Extensions\AIRIO.dll&quot; &quot;Extensions\AIRIO.dll&quot; 
        ///RMDIR /S /Q &quot;Updates&quot;
        ///ECHO Restarting VoiceAttack...
        ///START &quot;VoiceAttack&quot; /MIN XXXXXX
        ///ECHO Done!
        ///EXIT
        ///.
        /// </summary>
        public static string Updater_RIO {
            get {
                return ResourceManager.GetString("Updater_RIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;Profile xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///  &lt;HasMB&gt;false&lt;/HasMB&gt;
        ///  &lt;Id&gt;65ee8337-d43c-4b26-aea9-4ce0f9d4e467&lt;/Id&gt;
        ///  &lt;Name&gt;VAICOM PRO for DCS World&lt;/Name&gt;
        ///  &lt;Commands&gt;
        ///    &lt;Command&gt;
        ///      &lt;Referrer xsi:nil=&quot;true&quot; /&gt;
        ///      &lt;ExecType&gt;3&lt;/ExecType&gt;
        ///      &lt;Confidence&gt;0&lt;/Confidence&gt;
        ///      &lt;PrefixActionCount&gt;0&lt;/PrefixActionCount&gt;
        ///      &lt;IsDynamicallyCreated&gt;false&lt;/IsDynamicallyCreated&gt;
        ///      &lt;TargetProcessSet&gt;false&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string VAICOM_PRO_for_DCS_World {
            get {
                return ResourceManager.GetString("VAICOM_PRO_for_DCS_World", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] VAICOMPRO {
            get {
                object obj = ResourceManager.GetObject("VAICOMPRO", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon vaicompro_icon_32 {
            get {
                object obj = ResourceManager.GetObject("vaicompro_icon_32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap VAICOMPRO_logo_icon_5_128 {
            get {
                object obj = ResourceManager.GetObject("VAICOMPRO_logo_icon_5_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap VAICOMPRO_logo_icon_5_16 {
            get {
                object obj = ResourceManager.GetObject("VAICOMPRO_logo_icon_5_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Vox_Relay_Cold {
            get {
                object obj = ResourceManager.GetObject("Vox_Relay_Cold", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Vox_Relay_Hot {
            get {
                object obj = ResourceManager.GetObject("Vox_Relay_Hot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap YouTube {
            get {
                object obj = ResourceManager.GetObject("YouTube", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap YouTubePlay {
            get {
                object obj = ResourceManager.GetObject("YouTubePlay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
