<Project>
  <PropertyGroup>
	  <AssemblyTitle>VAICOM for DCS World</AssemblyTitle>
	  <Product>VAICOM Community Edition</Product>
	  <Description>Interactive Voice Control for DCS World</Description>
	  <ProductVersion>3.1.7.4</ProductVersion>
	  <AssemblyVersion>3.1.7.4</AssemblyVersion>
	  <FileVersion>3.1.7.4</FileVersion>
	  <Copyright>MIT</Copyright>
  </PropertyGroup>
</Project>
