//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Themepack {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Russia {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Russia() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Themepack.Russia", typeof(Russia).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_AF_3mins_01_ {
            get {
                return ResourceManager.GetStream("RUSSIA_AF_3mins_01_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_AF_3mins_02_ {
            get {
                return ResourceManager.GetStream("RUSSIA_AF_3mins_02_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_AF_3mins_03_ {
            get {
                return ResourceManager.GetStream("RUSSIA_AF_3mins_03_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_AF_3mins_04_ {
            get {
                return ResourceManager.GetStream("RUSSIA_AF_3mins_04_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_AF_3mins_05_ {
            get {
                return ResourceManager.GetStream("RUSSIA_AF_3mins_05_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_AF_3mins_06_ {
            get {
                return ResourceManager.GetStream("RUSSIA_AF_3mins_06_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_AF_3mins_07_ {
            get {
                return ResourceManager.GetStream("RUSSIA_AF_3mins_07_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_AF_3mins_08_ {
            get {
                return ResourceManager.GetStream("RUSSIA_AF_3mins_08_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_AF_3mins_09_ {
            get {
                return ResourceManager.GetStream("RUSSIA_AF_3mins_09_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_AF_3mins_10_ {
            get {
                return ResourceManager.GetStream("RUSSIA_AF_3mins_10_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_AF_3mins_11_ {
            get {
                return ResourceManager.GetStream("RUSSIA_AF_3mins_11_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_AF_3mins_12_ {
            get {
                return ResourceManager.GetStream("RUSSIA_AF_3mins_12_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_AF_3mins_13_ {
            get {
                return ResourceManager.GetStream("RUSSIA_AF_3mins_13_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_AF_3mins_14_ {
            get {
                return ResourceManager.GetStream("RUSSIA_AF_3mins_14_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_AF_3mins_15_ {
            get {
                return ResourceManager.GetStream("RUSSIA_AF_3mins_15_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_01_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_01_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_02_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_02_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_03_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_03_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_04_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_04_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_05_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_05_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_06_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_06_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_07_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_07_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_08_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_08_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_09_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_09_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_10_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_10_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_11_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_11_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_12_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_12_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_13_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_13_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_14_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_14_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_15_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_15_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_16_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_16_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_17_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_17_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_18_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_18_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_19_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_19_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_20_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_20_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_21_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_21_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_22_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_22_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_23_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_23_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_24_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_24_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_25_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_25_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_26_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_26_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_27_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_27_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_28_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_28_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_29_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_29_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_30_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_30_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_31_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_31_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_32_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_32_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_33_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_33_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_34_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_34_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_35_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_35_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_36_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_36_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_37_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_37_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_38_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_38_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_39_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_39_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_40_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_40_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_41_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_41_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_42_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_42_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_43_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_43_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_44_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_44_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_45_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_45_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_46_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_46_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_47_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_47_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_48_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_48_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_49_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_49_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_50_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_50_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_51_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_51_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_52_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_52_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_53_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_53_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_54_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_54_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_55_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_55_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_56_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_56_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_57_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_57_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_58_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_58_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_59_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_59_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_60_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_60_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_61_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_61_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_62_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_62_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_63_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_63_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_64_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_64_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_65_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_65_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_66_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_66_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_67_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_67_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_68_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_68_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_69_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_69_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_70_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_70_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_71_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_71_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_72_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_72_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_73_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_73_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_74_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_74_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_75_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_75_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_76_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_76_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_77_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_77_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_78_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_78_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_79_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_79_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_80_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_80_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_81_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_81_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_82_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_82_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_83_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_83_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_84_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_84_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_85_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_85_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_86_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_86_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream RUSSIA_bombers18mins_87_ {
            get {
                return ResourceManager.GetStream("RUSSIA_bombers18mins_87_", resourceCulture);
            }
        }
    }
}
