//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Themepack {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WWII {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WWII() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Themepack.WWII", typeof(WWII).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_01_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_01_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_02_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_02_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_03_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_03_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_05_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_05_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_07_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_07_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_10_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_10_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_11_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_11_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_12_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_12_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_13_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_13_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_14_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_14_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_15_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_15_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_16_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_16_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_17_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_17_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_18_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_18_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_19_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_19_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_20_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_20_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_21_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_21_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_22_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_22_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_24_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_24_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_25_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_25_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_26_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_26_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_27_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_27_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_28_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_28_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_29_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_29_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_30_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_30_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_31_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_31_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_32_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_32_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_33_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_33_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_34_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_34_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_35_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_35_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_36_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_36_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_37_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_37_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_38_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_38_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_39_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_39_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_40_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_40_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_41_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_41_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_42_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_42_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_43_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_43_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_44_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_44_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_45_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_45_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_46_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_46_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_47_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_47_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_48_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_48_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_49_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_49_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_50_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_50_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_51_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_51_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_52_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_52_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_53_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_53_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_54_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_54_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_55_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_55_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_56_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_56_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_57_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_57_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_58_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_58_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_59_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_59_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_60_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_60_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_61_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_61_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_62_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_62_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_1_63_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_1_63_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_2_01_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_2_01_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_2_02_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_2_02_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_2_03_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_2_03_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_2_04_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_2_04_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_2_05_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_2_05_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_2_06_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_2_06_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_2_07_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_2_07_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_2_08_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_2_08_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_2_09_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_2_09_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_2_10_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_2_10_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_2_11_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_2_11_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_2_12_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_2_12_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_2_13_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_2_13_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_2_14_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_2_14_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_2_15_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_2_15_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_2_16_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_2_16_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_2_17_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_2_17_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_2_18_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_2_18_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_2_19_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_2_19_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_2_20_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_2_20_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_2_21_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_2_21_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_2_22_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_2_22_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_2_23_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_2_23_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_2_24_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_2_24_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_2_25_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_2_25_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_2_26_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_2_26_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_2_27_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_2_27_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_2_28_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_2_28_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_2_29_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_2_29_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_6_01_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_6_01_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_6_02_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_6_02_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_6_03_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_6_03_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_6_04_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_6_04_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_6_05_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_6_05_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_6_06_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_6_06_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_6_07_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_6_07_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_6_08_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_6_08_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_6_09_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_6_09_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_6_10_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_6_10_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_6_11_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_6_11_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_6_12_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_6_12_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_6_13_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_6_13_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_6_14_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_6_14_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_6_15_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_6_15_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_6_16_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_6_16_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_6_17_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_6_17_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_6_18_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_6_18_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_6_19_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_6_19_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_6_20_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_6_20_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_6_21_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_6_21_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_6_22_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_6_22_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_6_23_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_6_23_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_6_24_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_6_24_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_6_25_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_6_25_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_6_26_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_6_26_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_01_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_01_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_02_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_02_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_03_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_03_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_04_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_04_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_05_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_05_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_06_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_06_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_07_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_07_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_08_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_08_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_09_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_09_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_10_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_10_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_11_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_11_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_12_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_12_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_13_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_13_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_14_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_14_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_15_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_15_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_16_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_16_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_17_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_17_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_18_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_18_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_19_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_19_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_20_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_20_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_21_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_21_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_22_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_22_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_23_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_23_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_24_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_24_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_25_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_25_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_26_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_26_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_27_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_27_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_28_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_28_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_29_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_29_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_30_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_30_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_31_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_31_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_32_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_32_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_33_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_33_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_34_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_34_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_35_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_35_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_36_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_36_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_37_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_37_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_38_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_38_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_39_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_39_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_40_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_40_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_41_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_41_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_42_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_42_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_43_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_43_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_44_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_44_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_45_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_45_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_46_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_46_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_47_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_47_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_48_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_48_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_49_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_49_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_50_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_50_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_51_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_51_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_52_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_52_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream WWII_RAW_part_7_53_ {
            get {
                return ResourceManager.GetStream("WWII_RAW_part_7_53_", resourceCulture);
            }
        }
    }
}
