using System;
using System.Collections.Generic;

namespace VAICOM.Extensions.CPG
{
    public static partial class Aliases
    {
        // Aliases for recipients (get added to recipient aliases)
        public static Dictionary<string, string> airecipients = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            // George AI aliases are currently unused as these are hardcoded into the commands themselves,
            // and the "Gunner" command aliases are generated on-the-fly.
            {
                "George", "george"
            }
        };

        // Aliases for CPG commands (get added to command aliases)
        public static Dictionary<string, string> aicommands = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            // Common - Button Control
            { "George Menu",                                 "georgeshowhide"                },
            { "George Show",                                 "georgeshowhide"                },
            { "George Hide",                                 "georgeshowhide"                },
            { "George Up",                                   "georgeup"                      },
            { "George Down",                                 "georgedown"                    },
            { "George Left",                                 "georgeleft"                    },
            { "George Right",                                "georgeright"                   },
            { "George Center",                               "georgecenter"                  },
            { "George Up Long",                              "georgeuplong"                  },
            { "George Down Long",                            "georgedownlong"                },
            { "George Left Long",                            "georgeleftlong"                },
            { "George Right Long",                           "georgerightlong"               },
            { "George Center Long",                          "georgecenterlong"              },
            { "George Request Control",                      "georgecontrolrequest"          },

            // CPG - Start and Shutdown
            { "George Start Up",                             "georgestartup"                 },
            { "George start your runup",                     "georgestartup"                 },
            { "George let's get going",                      "georgestartup"                 },
            { "George run-'er-up",                           "georgestartup"                 },
            { "George Shutdown",                             "georgeshutdown"                },
            { "George start your shutdown",                  "georgeshutdown"                },
            { "George shut-'er down",                        "georgeshutdown"                },
            { "George normal shutdown",                      "georgeshutdown"                },

            // CPG - Search and Sensor Management
            { "George TADS Sensor",                          "georgetadssensor"              },
            { "George TADS FLIR",                            "georgetadssensor"              },
            { "George TADS TV",                              "georgetadssensor"              },
            { "George swap sensors",                         "georgetadssensor"              },
            { "George cycle your sensor",                    "georgetadssensor"              },
            { "George next sensor",                          "georgetadssensor"              },
            { "George TADS F O V",                           "georgetadsfov"                 },
            { "George TADS Field Of View",                   "georgetadsfov"                 },
            { "George TADS Zoom In",                         "georgetadszoomin"              },
            { "George step in",                              "georgetadszoomin"              },
            { "George step in one field-of-view",            "georgetadszoomin"              },
            { "George step in a field-of-view",              "georgetadszoomin"              },
            { "George TADS Zoom Out",                        "georgetadszoomout"             },
            { "George step back out",                        "georgetadszoomout"             },
            { "George back out one field-of-view",           "georgetadszoomout"             },
            { "George step out one field-of-view",           "georgetadszoomout"             },
            { "George step out a field-of-view",             "georgetadszoomout"             },
            { "George Target List Filter",                   "georgetargetlistfilter"        },
            { "George Filter List",                          "georgetargetlistfilter"        },
            { "George Point List Filter Mode",               "georgepointlistfiltermode"     },
            { "George change waypoints and control measures", "georgepointlistfiltermode"    },
            { "George cycle waypoints and control measures",  "georgepointlistfiltermode"    },
            { "George Area Select",                          "georgeareaselect"              },
            { "George Point Select",                         "georgepointselect"             },
            { "George Point List Filter Threat",             "georgepointlistfilterthreat"   },
            { "George target points only",                   "georgepointlistfilterthreat"   },
            { "George target threats only",                  "georgepointlistfilterthreat"   },
            { "George focus on threats",                     "georgepointlistfilterthreat"   },
            { "George focus on threats only",                "georgepointlistfilterthreat"   },
            { "George Search Area",                          "georgeareasearch"              },
            { "George search your area",                     "georgeareasearch"              },
            { "George start searching for targets",          "georgeareasearch"              },
            { "George start scanning for targets in the area", "georgeareasearch"            },
            { "George scan for targets in the area",         "georgeareasearch"              },
            { "George watch your lane",                      "georgeareasearch"              },
            { "George Search Point",                         "georgepointsearch"             },
            { "George search for targets around that point", "georgepointsearch"             },
            { "George search for targets near that point",   "georgepointsearch"             },
            { "George scan for targets at the selected point", "georgepointsearch"           },
            { "George Next Search",                          "georgemacronextsearch"         },
            { "George Search Next",                          "georgemacronextsearch"         },
            { "George Previous Search",                      "georgemacroprevioussearch"     },
            { "George Search Previous",                      "georgemacroprevioussearch"     },
            { "George Next Point",                           "georgemacronextpoint"          },
            { "George Point Next",                           "georgemacronextpoint"          },
            { "George Previous Point",                       "georgemacropreviouspoint"      },
            { "George Point Previous",                       "georgemacropreviouspoint"      },
            { "George P H S",                                "georgemacrophssearch"          },
            { "George target pilot helmet sight",            "georgemacrophssearch"          },
            { "George target pilot H M D",                   "georgemacrophssearch"          },
            { "George Pilot Helmet Search",                  "georgemacrophssearch"          },
            { "George My Line Of Sight",                     "georgemacrophssearch"          },
            { "George TADS L O S",                           "georgemacrotadslos"            },
            { "George TADS Line Of Sight",                   "georgemacrotadslos"            },
            { "George what do you see there",                "georgemacrotadslos"            },
            { "George any targets there",                    "georgemacrotadslos"            },
            { "George what's in your line-of-sight",         "georgemacrotadslos"            },
            { "George what's that",                          "georgemacrotadslos"            },

            // CPG - Weapons and Targeting
            { "George Next Weapon",                          "georgenextweapon"              },
            { "George Select Gun",                           "georgemacroselectgun"          },
            { "George Select Missiles",                      "georgemacroselectmissiles"     },
            { "George Select Rockets",                       "georgemacroselectrockets"      },
            { "George Select No Weapon",                     "georgemacroselectnoweapon"     },
            { "George Wahz the Gun",                         "georgemacroselectgun"          },
            { "George Wahz Missiles",                        "georgemacroselectmissiles"     },
            { "George Wahz Rockets",                         "georgemacroselectrockets"      },
            { "George De Wahz",                              "georgemacroselectnoweapon"     },
            { "George lase target",                          "georgelasetarget"              },
            { "George laser On",                             "georgelaseron"                 },
            { "George clear to lase",                        "georgelaseron"                 },
            { "George start lasing",                         "georgelaseron"                 },
            { "George designate the target",                 "georgelaseron"                 },
            { "George laser Off",                            "georgelaseroff"                },
            { "George cease lasing",                         "georgelaseroff"                },
            { "George stop lasing",                          "georgelaseroff"                },
            { "George stop designating the target",          "georgelaseroff"                },
            { "George Burst Limit",                          "georgeburstlimit"              },
            { "George next burst limit",                     "georgeburstlimit"              },
            { "George cycle burst limit",                    "georgeburstlimit"              },
            { "George Rocket Quantity",                      "georgerocketquantity"          },
            { "George next quantity",                        "georgerocketquantity"          },
            { "George cycle quantity",                       "georgerocketquantity"          },
            { "George Next Rocket",                          "georgenextrkt"                 },
            { "George Switch Rocket Type",                   "georgenextrkt"                 },
            { "George next rocket zone",                     "georgenextrkt"                 },
            { "George select next zone",                     "georgenextrkt"                 },
            { "George Change trajectory",                    "georgemsltraj"                 },
            { "George Next Trajectory",                      "georgemsltraj"                 },
            { "George Previous Missile",                     "georgenextmsl"                 },
            { "George Next Missile",                         "georgenextmsl"                 },
            { "George go SAL",                               "georgenextmsl"                 },
            { "George go R F",                               "georgenextmsl"                 },
            { "George L O B L",                              "georgelobl"                    },
            { "George, go low-ball",                         "georgelobl"                    },
            { "George Low ball",                             "georgeloal"                    },
            { "George L O A L",                              "georgelobl"                    },
            { "George Low Al",                               "georgeloal"                    },
            { "George, go low-al",                           "georgeloal"                    },
            { "George Target Zoom In",                       "georgetargetlistzoomin"        },
            { "George Target Zoom Out",                      "georgetargetlistzoomout"       },
            { "George Previous Item",                        "georgepreviousitem"            },
            { "George Previous List Area",                   "georgepreviousitem"            },
            { "George Previous List Point",                  "georgepreviousitem"            },
            { "George Next Item",                            "georgenextitem"                },
            { "George Next List Area",                       "georgenextitem"                },
            { "George Next List Point",                      "georgenextitem"                },
            { "George Previous Target",                      "georgepreviuoustarget"         },
            { "George Next Target",                          "georgenexttarget"              },
            { "George List Item Select",                     "georgelistitemselect"          },
            { "George Select That Area",                     "georgelistitemselect"          },
            { "George Select That Point",                    "georgelistitemselect"          },
            { "George Add and Track Your Top Two",           "georgemacroaddtwotargetstrack" },
            { "George Add and Track Your Top Three",         "georgemacroaddthreetargetstrack" },
            { "George Add and Track Your Top Four",          "georgemacroaddfourtargetstrack" },
            { "George Track Your Top Two",                   "georgemacroaddtwotargetstrack" },
            { "George Track Your Top Three",                 "georgemacroaddthreetargetstrack" },
            { "George Track Your Top Four",                  "georgemacroaddfourtargetstrack" },
            { "George Track and Engage",                     "georgemacrotrackengage"        },
            { "George Select Target",                        "georgeselecttarget"            },
            { "George Add Target",                           "georgeselecttarget"            },
            { "George Track Target",                         "georgetracktarget"             },
            { "George Store Target",                         "georgestoretarget"             },
            { "George store that target",                    "georgestoretarget"             },
            { "George Last Stored Target",                   "georgelaststoredtarget"        },
            { "George Go To Last Target",                    "georgelastfoundtarget"         },
            { "George Exit Target List",                     "georgeexitlist"                },
            { "George disregard those targets",              "georgeexitlist"                },
            { "George ignore those",                         "georgeexitlist"                },
            { "George ignore those targets",                 "georgeexitlist"                },
            { "George Adjust Aim",                           "georgeadjustaim"               },
            { "George Adjust your Aim",                      "georgeadjustaim"               },
            { "George center your aimpoint",                 "georgeadjustaim"               },
            { "George center on target",                     "georgeadjustaim"               },
            { "George put the Line-of-sight on the target",  "georgeadjustaim"               },
            { "George Clear to Fire",                        "georgeclearedfire"             },
            { "George Hit Them Again",                       "georgeclearedfire"             },
            { "George Clear to Engage",                      "georgeclearedfire"             },
            { "George Weapons Free",                         "georgeweaponsfree"             },
            { "George Engage at Will",                       "georgeweaponsfree"             },
            { "George Fire at Will",                         "georgeweaponsfree"             },
            { "George Hold Fire",                            "georgeholdfire"                },
            { "George Hold Your Fire",                       "georgeholdfire"                },
            { "George Cease Fire",                           "georgeholdfire"                },

            // Pilot - Startup, Shutdown, and Takeoff (GND)
            { "George Start A P U",                          "georgestartupapu"              },
            { "George Start Engines Idle",                   "georgestartupenginesidle"      },
            { "George Start Engines Fly",                    "georgestartupenginesfly"       },
            { "George Full Start Up",                        "georgestartupfull"             },
            { "George Full Shutdown",                        "georgeshutdownfull"            },
            { "George Shutdown Engines",                     "georgeshutdownengines"         },
            { "George Take Off",                             "georgetakeoff"                 },

            // Pilot - Flight and Navigation (FLT)
            { "George Speed Up",                             "georgespeedup"                 },
            { "George Slow Down",                            "georgeslowdown"                },
            { "George Increase Altitude",                    "georgeincreasealtitude"        },
            { "George Decrease Altitude",                    "georgedecreasealtitude"        },
            { "George Follow Waypoints",                     "georgefollowwaypoints"         },
            { "George Come Left",                            "georgecomeleft"                },
            { "George Come Right",                           "georgecomeright"               },
            { "George Set Air Speed",                        "georgesetairspeedref"          },
            { "George Set Ground Speed",                     "georgesetgroundspeedref"       },
            { "George Set Radar Altitude",                   "georgesetradaraltitude"        },
            { "George Set Barometric Altitude",              "georgesetbarometricaltitude"   },

            // Pilot - Combat Maneuvers (CMBT)
            { "George Break Left",                           "georgebreakleft"               },
            { "George Break Right",                          "georgebreakright"              },
            { "George Orbit Overhead",                       "georgeorbitoverhead"           },
            { "George Break One Eighty",                     "georgebreakoneeighty"          },
            { "George Head To Location",                     "georgeheadtolocation"          },
            { "George Align To TADS",                        "georgealigntotads"             },
            { "George Align To N T S",                       "georgealigntonts"              },
            { "George Align To Next To Shoot",               "georgealigntonts"              },
            { "George Turn To G H S",                        "georgeturntoghs"               },
            { "George Turn To Gunner Helmet Sight",          "georgeturntoghs"               },
            { "George Hold Position",                        "georgeholdposition"            },
            { "George Add Battle Position",                  "georgeaddbattleposition"       },
            { "George Delete Battle Position",               "georgedeletebattleposition"    },
            { "George Return To Battle Position",            "georgereturntobattleposition"  },
            { "George Mask Position",                        "georgemaskposition"            },

            // Pilot - Defense (DEFN)
            { "George Return Fire",                          "georgereturnfire"              },
            { "George Evade Off",                            "georgeevadeoff"                },
            { "George Evade Level",                          "georgeevadelevel"              },
            { "George Evade Vertical",                       "georgeevadevertical"           },
            { "George Evade Mask",                           "georgeevademask"               },
            { "George Threat Warnings On",                   "georgethreatwarningson"        },
            { "George Threat Warnings Off",                  "georgethreatwarningsoff"       },
            { "George Countermeasures Arm",                  "georgecmwsarm"                 },
            { "George Countermeasures Safe",                 "georgecmwssafe"                },
            { "George Countermeasures Auto",                 "georgecmwsauto"                },
            { "George Countermeasures Bypass",               "georgecmwsbypass"              },
            { "George Dispense None",                        "georgecmdispensenone"          },
            { "George Dispense Chaff",                       "georgecmdispensechaff"         },
            { "George Dispense Flares",                      "georgecmdispenseflares"        },
            { "George Dispense Chaff And Flares",            "georgecmdispensechaffandflares" },
            { "George Turn Off Lights",                      "georgeextlightsoff"            },
            { "George Turn On Day Lights",                   "georgeextlightsday"            },
            { "George Turn On Night Lights",                 "georgeextlightsnightbright"    },
            { "George Turn On Dim Lights",                   "georgeextlightsnightdim"       },
            { "George Turn On Formation Lights",             "georgeextlightsformation"      },

            // Pilot - Hover Bob-up (H-B)
            { "George Move Forwards",                        "georgehoverforward"            },
            { "George Move Back",                            "georgehoverback"               },
            { "George Move Left",                            "georgehoverleft"               },
            { "George Move Right",                           "georgehoverright"              },
            { "George Come Up 10 Feet",                      "georgehoveruptenfeet"          },
            { "George Come Down 10 Feet",                    "georgehoverdowntenfeet"        },

            // Pilot - Menu Modes
            { "George Combat Mode",                          "georgemenucombatmode"          },
            { "George Defense Mode",                         "georgemenudefensemode"         },
            { "George Flight Mode",                          "georgemenuflightmode"          },
            { "George Ground Mode",                          "georgemenugroundmode"          },
            { "George Hover Mode",                           "georgemenuhovermode"           },
            { "George Next Mode",                            "georgemenunextmode"            },
        };
    }
}