using System;
using System.Collections.Generic;

namespace VAICOM.Extensions.CPG
{
    public static partial class Labels
    {
        // Labels for George AI recipients
        public static Dictionary<string, string> airecipients = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            { "george", "AH-64D AI CP/G" }
        };

        // Labels for George AI commands
        public static Dictionary<string, string> aicommands = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            { "georgeshowhide",                     "George Show/Hide"      },
            { "georgeup",                           "George Up"             },
            { "georgedown",                         "George Down"           },
            { "georgeleft",                         "George Left"           },
            { "georgeright",                        "George Right"          },
            { "georgecenter",                       "George Select"         },
            { "georgecontrolrequest",               "George Request Control"},
            { "georgestoretarget",                  "George Store Target"   },
            { "georgeuplong",                       "George Up (Hold)"      },
            { "georgedownlong",                     "George Down (Hold)"    },
            { "georgeleftlong",                     "George Left (Hold)"    },
            { "georgerightlong",                    "George Right (Hold)"   },
            { "georgecenterlong",                   "George Select (Hold)"  },
            { "georgemacrophssearch",               "George PHS Search"    },
            { "georgemacrotadslos",                 "George TADS LOS"       },
            { "georgemacronextsearch",              "George Next Search" },
            { "georgemacroprevioussearch",          "George Previous Search" },
            { "georgemacronextpoint",               "George Next Point" },
            { "georgemacropreviouspoint",           "George Previous Point" },
            { "georgelasetarget",                   "George Lase Target" },
            { "georgelaseron",                      "George Laser On" },
            { "georgelaseroff",                     "George Laser Off" },
            { "georgeburstlimit",                   "George Burst Limit" },
            { "georgerocketquantity",               "George Rocket Quantity" },
            { "georgelobl",                         "George LOBL" },
            { "georgeloal",                         "George LOAL" },
            { "georgenextweapon",                   "George Next Weapon" },
            { "georgeclearedfire",                  "George Cleared Fire" },
            { "georgeweaponsfree",                  "George Weapons Free" },
            { "georgeholdfire",                     "George Hold Fire" },
            { "georgestartup",                      "George Start Up" },
            { "georgeshutdown",                     "George Shutdown" },
            { "georgeadjustaim",                    "George Adjust Aim" },
            { "georgetadssensor",                   "George TADS Sensor" },
            { "georgetadsfov",                      "George TADS FOV" },
            { "georgetargetlistfilter",             "George Target List Filter" },
            { "georgepointlistfiltermode",          "George Point List Filter Mode" },
            { "georgepointlistfilterthreat",        "George Point List Filter Threat" },
            { "georgetargetlistzoomin",             "George Target List Zoom In" },
            { "georgetargetlistzoomout",            "George Target List Zoom Out" },
            { "georgepreviuoustarget",              "George Previous Target" },
            { "georgenexttarget",                   "George Next Target" },
            { "georgeexitlist",                     "George Exit List" },
            { "georgetracktarget",                  "George Track Target" },
            { "georgetadszoomin",                   "George TADS Zoom In" },
            { "georgetadszoomout",                  "George TADS Zoom Out" },
            { "georgenextrkt",                      "George Next Rocket" },
            { "georgemsltraj",                      "George Missile Trajectory" },
            { "georgeselecttarget",                 "George Select Target" },
            { "georgepreviousitem",                 "George Previous Item" },
            { "georgenextitem",                     "George Next Item" },
            { "georgelistitemselect",               "George List Item Select" },
            { "georgeareasearch",                   "George Area Search" },
            { "georgepointsearch",                  "George Point Search" },
            { "georgelaststoredtarget",             "George Last Stored Target" },
            { "georgeareaselect",                   "George Area Select" },
            { "georgepointselect",                  "George Point Select" },
            { "georgemacroaddtwotargetstrack",      "George Add and Track Top 2 Targets" },
            { "georgemacroaddthreetargetstrack",    "George Add and Track Top 3 Targets" },
            { "georgemacroaddfourtargetstrack",     "George Add and Track Top 4 Targets" },
            { "georgelastfoundtarget",              "George Last Found Target" },
            { "georgemacrotrackengage",             "George Track and Engage" },
            { "georgemacroselectgun",               "George Select Gun" },
            { "georgemacroselectmissiles",          "George Select Missiles" },
            { "georgemacroselectrockets",           "George Select Rockets" },
            { "georgemacroselectnoweapon",          "George Select No Weapon" },
            { "georgenextmsl",                      "George Next Missile Type" },

            { "georgestartupapu",                   "George Start APU" },
            { "georgestartupenginesidle",           "George Start Engines Idle" },
            { "georgestartupenginesfly",            "George Start Engines Fly" },
            { "georgestartupfull",                  "George Full Start Up" },
            { "georgeshutdownfull",                 "George Full Shutdown" },
            { "georgeshutdownengines",              "George Shutdown Engines" },
            { "georgetakeoff",                      "George Take Off" },
            { "georgespeedup",                      "George Speed Up" },
            { "georgeslowdown",                     "George Slow Down" },
            { "georgeincreasealtitude",             "George Increase Altitude" },
            { "georgedecreasealtitude",             "George Decrease Altitude" },
            { "georgefollowwaypoints",              "George Follow Waypoints" },
            { "georgecomeleft",                     "George Come Left" },
            { "georgecomeright",                    "George Come Right" },
            { "georgesetairspeedref",               "George Set Air Speed Reference" },
            { "georgesetgroundspeedref",            "George Set Ground Speed Reference" },
            { "georgesetradaraltitude",             "George Set Radar Altitude" },
            { "georgesetbarometricaltitude",        "George Set Barometric Altitude" },
            { "georgebreakleft",                    "George Break Left" },
            { "georgebreakright",                   "George Break Right" },
            { "georgeorbitoverhead",                "George Orbit Overhead" },
            { "georgebreakoneeighty",               "George Break One Eighty" },
            { "georgeheadtolocation",               "George Head To Location" },
            { "georgealigntotads",                  "George Align To TADS" },
            { "georgealigntonts",                   "George Align To NTS" },
            { "georgeturntoghs",                    "George Turn To GHS" },
            { "georgeholdposition",                 "George Hold Position" },
            { "georgeaddbattleposition",            "George Add Battle Position" },
            { "georgedeletebattleposition",         "George Delete Battle Position" },
            { "georgereturntobattleposition",       "George Return To Battle Position" },
            { "georgemaskposition",                 "George Mask Position" },
            { "georgereturnfire",                   "George Return Fire" },
            { "georgeevadeoff",                     "George Evade Off" },
            { "georgeevadelevel",                   "George Evade Level" },
            { "georgeevadevertical",                "George Evade Vertical" },
            { "georgeevademask",                    "George Evade Mask" },
            { "georgethreatwarningson",             "George Threat Warnings On" },
            { "georgethreatwarningsoff",            "George Threat Warnings Off" },
            { "georgecmwsarm",                      "George Countermeasures Arm" },
            { "georgecmwssafe",                     "George Countermeasures Safe" },
            { "georgecmwsauto",                     "George Countermeasures Auto" },
            { "georgecmwsbypass",                   "George Countermeasures Bypass" },
            { "georgecmdispensenone",               "George Dispense None" },
            { "georgecmdispensechaff",              "George Dispense Chaff" },
            { "georgecmdispenseflares",             "George Dispense Flares" },
            { "georgecmdispensechaffandflares",     "George Dispense Chaff And Flares" },
            { "georgeextlightsoff",                 "George Turn Off Lights" },
            { "georgeextlightsday",                 "George Turn On Day Lights" },
            { "georgeextlightsnightbright",         "George Turn On Night Lights" },
            { "georgeextlightsnightdim",            "George Turn On Dim Lights" },
            { "georgeextlightsformation",           "George Turn On Formation Lights" },
            { "georgehoverforward",                 "George Move Forwards" },
            { "georgehoverback",                    "George Move Back" },
            { "georgehoverleft",                    "George Move Left" },
            { "georgehoverright",                   "George Move Right" },
            { "georgehoveruptenfeet",               "George Come Up 10 Feet" },
            { "georgehoverdowntenfeet",             "George Come Down 10 Feet" },
            { "georgemenucombatmode",               "George Combat Mode" },
            { "georgemenudefensemode",              "George Defense Mode" },
            { "georgemenuflightmode",               "George Flight Mode" },
            { "georgemenugroundmode",               "George Ground Mode" },
            { "georgemenuhovermode",                "George Hover Mode" },
            { "georgemenunextmode",                 "George Next Mode" },
        };
    }
}