cdata =
{
	VAICOM_TITLE		= '$HEADER$',
	VAICOM_VERSION		= '$VERSION$',
	VAICOM_LICENSE		= '$LICENSE$',

	VAICOM_DLLPLUGIN	= '$DLLPLUGIN$',
	VAICOM_DLLCHATTER	= '$DLLCHATTER$',
	VAICOM_DLLRIO		= '$DLLRIO$',

	VAICOM_IPCONFIG		= '$IPCONFIG$',
	VAICOM_CLIENTIP_TXT	= '$CLIENTIPTXT$',

	VAICOM_FOOTER		= '$FOOTER$',
}
